insert into storage.buckets (id, name, public)
values ('movie-posters', 'movie-posters', true)
on conflict (id) do update set public = excluded.public;

create table if not exists public.result_feedback (
    id bigint generated by default as identity primary key,
    query text not null,
    movie_id bigint not null,
    movie_title text not null,
    relevant boolean not null,
    created_at timestamptz not null default now()
);

alter table public.result_feedback enable row level security;
grant insert on public.result_feedback to service_role;
grant usage, select on sequence public.result_feedback_id_seq to service_role;